--DEMOGRAPHIC DATA
SELECT COUNT(*) 
FROM DEMO
ORDER BY 고객번호;

--제휴사별 경쟁사 이용현황
SELECT * FROM COMPET;

--멤버십
SELECT * FROM MEMBERSHIP;

--상품분류
SELECT * FROM PRODCL;

--구매데이터
SELECT COUNT(*) FROM PURPROD;
SELECT * FROM PURPROD;

--구매합계
SELECT SUM(구매금액)
FROM PURPROD;

--PURPROD 복사
CREATE TABLE PURPROD1 AS SELECT * FROM PURPROD;

--연도별 구매합계
ALTER TABLE PURPROD1 ADD YEAR DATE;
ALTER TABLE PURPROD1 MODIFY YEAR VARCHAR2(20);
UPDATE PURPROD1 SET YEAR=SUBSTR(구매일자,1,4);
COMMIT;

SELECT YEAR, SUM(구매금액) 구매액
FROM PURPROD1
GROUP BY YEAR;

CREATE TABLE AMT14
AS SELECT 고객번호, 제휴사, SUM(구매금액) 구매금액 
FROM PURPROD
WHERE 구매일자 < 20150101
GROUP BY 고객번호, 제휴사
ORDER BY 고객번호;

select * from amt14;

CREATE TABLE AMT15
AS SELECT 고객번호, 제휴사, SUM(구매금액) 구매금액 
FROM PURPROD
WHERE 구매일자 > 20141231
GROUP BY 고객번호, 제휴사
ORDER BY 고객번호;

select * from amt15;

--FULL OUTER JOIN 테이블 생성
CREATE TABLE AMT_YEAR_FOJ
AS SELECT A4.고객번호, A4.제휴사, A4.구매금액 구매14, A5.구매금액 구매15
FROM AMT14 A4 FULL OUTER JOIN AMT15 A5
ON (A4.고객번호=A5.고객번호 AND A4.제휴사=A5.제휴사);

--FULL OUTER JOIN 적용시 증감 출력
SELECT 고객번호,제휴사, NVL(구매14,0) 구매14, NVL(구매15,0) 구매15,
(NVL(구매15,0)-NVL(구매14,0)) 증감
FROM AMT_YEAR_FOJ A;

--반기별 구매금액
ALTER TABLE PURPROD1 ADD MONTH VARCHAR2(20);
UPDATE PURPROD1 SET MONTH=SUBSTR(구매일자,1,6);
COMMIT;

DESC PURPROD1;
ALTER TABLE PURPROD1 ADD HYEAR VARCHAR2(20);

UPDATE PURPROD1 
SET HYEAR=
CASE WHEN MONTH <=201406 THEN '20141H'
WHEN MONTH <=201412 THEN '20142H'
WHEN MONTH <=201506 THEN '20151H'
ELSE '20152H' 
END;
COMMIT;
SELECT * FROM PURPROD1;

SELECT HYEAR, ROUND((SUM(구매금액)/1000000)) 반기구매_백만, ROUND(AVG(구매금액)) 평균구매 
FROM PURPROD1
GROUP BY HYEAR
ORDER BY HYEAR;

DESC PURPROD1;

--고객별 구매합계
SELECT 고객번호, SUM(구매금액) 구매액
FROM PURPROD1
GROUP BY 고객번호
ORDER BY 고객번호;

--고객별 제휴사별 기준 합계
SELECT 고객번호, 제휴사, SUM(구매금액) 구매액
FROM PURPROD1
GROUP BY 고객번호, 제휴사
ORDER BY 고객번호;

--고객별 제휴사별 상품대분류 기준 합계
SELECT 고객번호, 제휴사, 대분류코드, SUM(구매금액) 구매액
FROM PURPROD1
GROUP BY 고객번호, 제휴사, 대분류코드
ORDER BY 고객번호;

--과제8_0511. lm 데이터 테이블 6개로 l사의 비즈 현황을 파악할 수 있는 요약 테이블을 
--5개 이상 생성하고 설명하세요.

--테이블 결합 : DEMO + PURPROD
SELECT d.고객번호, SUM(p.HYEAR='201406'), sum(p.HYEAR='201412') 
FROM DEMO d, PURPROD1 p
WHERE d.고객번호 = p.고객번호
GROUP BY d.고객번호;

--고객별 구매금액의 합계를 구한 CUSPUR 테이블을 생성
SELECT * FROM PURPROD1;

CREATE TABLE CUSPUR
AS SELECT 고객번호, 
SUM(CASE WHEN HYEAR='20141H' THEN 구매금액 ELSE 0 END) AS H1,
SUM(CASE WHEN HYEAR='20142H' THEN 구매금액 ELSE 0 END) AS H2,
SUM(CASE WHEN HYEAR='20151H' THEN 구매금액 ELSE 0 END) AS H3,
SUM(CASE WHEN HYEAR='20152H' THEN 구매금액 ELSE 0 END) AS H4
FROM PURPROD1
GROUP BY 고객번호
ORDER BY 고객번호;
SELECT * FROM CUSPUR;

--DEMO와 CUSPUR 고객번호 기준 결합 : CUSDP
DESC DEMO;
DROP TABLE CUSDP;
CREATE TABLE CUSDP
AS SELECT CP.*, D.성별, D.연령대, D.거주지역
FROM CUSPUR CP, DEMO D 
WHERE D.고객번호 = CP.고객번호;

CREATE TABLE CUSDEPU
AS SELECT * 
FROM CUSDP
ORDER BY 고객번호;

SELECT * FROM CUSDEPU;

--과제1_0512. LM 사업 현안을 파악할 수 있는 전체, 고객, 상품별 테이블을 3개 이상 작성하세요.
